require:
  - rubocop-rspec
  - rubocop-rails

AllCops:
  Include:
    - Rakefile
    - config.ru
    - lib/**/*.rake
  Exclude:
    - db/schema.rb
    - vendor/**/*
    - bin/**/*
  TargetRubyVersion: 3.3.2
  NewCops: enable

#################### Style ####################

Style/AsciiComments:
  Description: Use only ascii symbols in comments.
  Enabled: false

AsciiIdentifiers:
  Description: Use only ascii symbols in identifiers.
  Enabled: false

Layout/LineLength:
  Max: 120
  Enabled: true

Metrics/MethodLength:
  Max: 20
  Enabled: true
