#inherit_from: .rubocop_todo.yml
require:
  - rubocop-rspec
  - rubocop-rails

AllCops:
  Include:
    - Rakefile
    - config.ru
    - lib/**/*.rake
  Exclude:
    - db/schema.rb
  TargetRubyVersion: 3.1.2
  NewCops: enable

#################### Style ####################

AsciiComments:
  Description: Use only ascii symbols in comments.
  Enabled: false

AsciiIdentifiers:
  Description: Use only ascii symbols in identifiers.
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 20
